// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyStudent.proto

package com.learn.demo.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.learn.demo.proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   * @return The requestInfo.
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   * @return The bytes for requestInfo.
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
