// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyStudent.proto

package com.learn.demo.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.learn.demo.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
